### ISSUE TITLE
problems with python 3.8 in timezones

### ISSUE THREAD

**Issue by ThomasChiroux** [dgilland/zulu#26]
example from python 3.8

```ipython
Python 3.8.1 (default, Jan  8 2020, 23:09:20)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from dateutil import tz

In [2]: import zulu

In [3]: n = zulu.now()

In [4]: n
Out[4]: <Zulu [2020-01-14T22:37:07.389997+00:00]>

In [5]: n.astimezone(tz.gettz("Europe/Paris"))
Out[5]: <Zulu [2020-01-14T22:37:07.389997+00:00]>

In [6]: n.datetime.astimezone(tz.gettz("Europe/Paris"))
Out[6]: datetime.datetime(2020, 1, 14, 23, 37, 7, 389997, tzinfo=tzfile('/usr/share/zoneinfo/Europe/Paris'))
```

Also tried to update tox in a zulu fork and test branch: all unittests are OK in python 3.7 and less, but  not ok in python 3.8:
https://travis-ci.com/ThomasChiroux/zulu/builds/144422588

This may have been related to this python bug:
https://bugs.python.org/issue32417 which has been merged in python 3.8

still investigating...
(a work around could be as seen in the example to call datetime before astimezone and force a cast to datetime before calling astimezone, but it's less powerfull than standard zulu lib (no timezone parsing)

**Comment by dgilland** [comment]
It turned out that in Python <= 3.7, in `Zulu.astimezone`, the `super().astimezone()` call returned a `datetime` instance but in 3.8, it returns another `Zulu` instance. The desired behavior was that a `datetime` should be returned. I had the wrong return type specified in the docstring but tests did assume that the return type should be `datetime`.

I fixed those in 7ae7d75 and then added 3.8 testing to tox and travis. I'll be releasing a new version that includes this fix as well as your #25.

Thanks for reporting the bug!
